const SIGN_IN_ADMIN = 'SIGN_IN_ADMIN';
const SIGN_OUT_ADMIN = 'SIGN_OUT_ADMIN';

const SIGN_IN_COMPANY = 'SIGN_IN_COMPANY';
const SIGN_OUT_COMPANY = 'SIGN_OUT_COMPANY';

const SIGN_IN_BUGHUNTER = 'SIGN_IN_BUGHUNTER';
const SIGN_OUT_BUGHUNTER = 'SIGN_OUT_BUGHUNTER';

export {
  SIGN_IN_ADMIN,
  SIGN_OUT_ADMIN,
  SIGN_IN_COMPANY,
  SIGN_OUT_COMPANY,
  SIGN_IN_BUGHUNTER,
  SIGN_OUT_BUGHUNTER,
};
